version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    working_dir: /var/www/html
    volumes:
      - ./sites/:/var/www/html
      - ./dev/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/docker/nginx/include/:/etc/nginx/include
      - ./dev/docker/nginx/sites-enabled/:/etc/nginx/sites-enabled
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    networks:
      - lamp-network

  php:
    build:
      context: ./dev/docker/php-fpm
      args:
        UID: $UID
        GUID: $GUID
        COMPOSER_VER: $COMPOSER_VER
        PHP_VER: $PHP_VER
    container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mailhog
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      # By default xdebug extension also disabled.
      PHP_EXTENSIONS_DISABLE: 'xhprof,xdebug'
    volumes:
      - ./dev/:/var/www/dev
      - ./sites/:/var/www/html
    networks:
      - lamp-network

  db:
    image: mysql:8
    container_name: "${PROJECT_NAME}_db"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 3306
    volumes:
      - ./dev/docker/mysql/data:/var/lib/mysql
    networks:
      - lamp-network

  pma:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $DB_ROOT_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      UPLOAD_LIMIT: 1G
    ports:
      - "${PMA_PORT}:80"
    networks:
      - lamp-network

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025"
      - "8025:8025"
    networks:
      - lamp-network


networks:
  lamp-network:
    driver: bridge
